import { contextBridge, ipcRenderer } from 'electron'

type WindowControlAction = 'minimize' | 'maximize' | 'close'

export interface CaptionTrack {
  languageCode: string
  languageName: string
  isAutoGenerated: boolean
}

export interface SubtitleItem {
  start: number
  dur: number
  text: string
}

export interface FetchCaptionsResult {
  success: boolean
  captions: CaptionTrack[]
  error?: string
}

export interface FetchSubtitlesResult {
  success: boolean
  subtitles: SubtitleItem[]
  error?: string
}

contextBridge.exposeInMainWorld('electronAPI', {
  platform: process.platform,
  // Electron store methods for redux-persist
  storeGet: (key: string): Promise<string | null> =>
    ipcRenderer.invoke('electron-store-get', key),
  storeSet: (key: string, value: string): Promise<boolean> =>
    ipcRenderer.invoke('electron-store-set', key, value),
  storeRemove: (key: string): Promise<boolean> =>
    ipcRenderer.invoke('electron-store-remove', key),
  windowControl: (action: WindowControlAction) =>
    ipcRenderer.send('window-control', action),
})
